name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        pytorch-lightning-version: ["1.8", "1.9"]
        pytorch-version: ["1.11"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}
      - pytorch-lightning=${{ matrix.pytorch-lightning-version }}
      - pytorch=${{ matrix.pytorch-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: env.yml
          environment-name: molfeat-padel
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Run pytest
        run: pytest

      - name: Run doc building
        run: mkdocs build
